from lib import (
    ActionDef,
    ColumnDef,
    FKDefinition,
    PKConfig,
    StateTransition,
    TableConfig,
)

config = TableConfig(
    table_name="approval_record",
    pk_field="flow_request_id",
    pk_config=PKConfig(strategy="custom", generator=lambda data: data["flow_request_id"]),
    states=['pending', 'verifying', 'approved', 'rework', 'cancelled', 'applied'],
    transitions=[
        StateTransition(from_state="init", to_state="pending"),
        StateTransition(from_state="pending", to_state="cancelled"),
        StateTransition(from_state="pending", to_state="approved"),
        StateTransition(from_state="pending", to_state="verifying"),
        StateTransition(from_state="pending", to_state="rework"),
        StateTransition(from_state="verifying", to_state="approved"),
        StateTransition(from_state="verifying", to_state="rework"),
        StateTransition(from_state="rework", to_state="cancelled"),
        StateTransition(from_state="rework", to_state="pending"),
        StateTransition(from_state="approved", to_state="applied"),
    ],
    columns=[
        ColumnDef(name="flow_request_id", pg_type="text", nullable=False),
        ColumnDef(name="domain_name", pg_type="varchar(255)", nullable=True),
        ColumnDef(name="entity_id", pg_type="text", nullable=True),
        ColumnDef(name="requested_by", pg_type="text", nullable=True),
        ColumnDef(name="requested_at", pg_type="timestamp", nullable=True),
        ColumnDef(name="first_approved_by", pg_type="text", nullable=True),
        ColumnDef(name="first_approved_at", pg_type="timestamp", nullable=True),
        ColumnDef(name="first_approved_comment", pg_type="text", nullable=True),
        ColumnDef(name="second_approved_by", pg_type="text", nullable=True),
        ColumnDef(name="second_approved_at", pg_type="timestamp", nullable=True),
        ColumnDef(name="second_approved_comment", pg_type="text", nullable=True),
        ColumnDef(name="applied_at", pg_type="timestamp", nullable=True),
        ColumnDef(name="ui_code", pg_type="text", nullable=True),
        ColumnDef(name="ui_name", pg_type="text", nullable=True),
        ColumnDef(name="ui_display_i", pg_type="text", nullable=True),
        ColumnDef(name="ui_display_ii", pg_type="text", nullable=True),
        ColumnDef(name="ui_display_iii", pg_type="text", nullable=True),
        ColumnDef(name="ui_display_iv", pg_type="text", nullable=True),
        ColumnDef(name="ui_display_v", pg_type="text", nullable=True),
        ColumnDef(name="state", pg_type="text", nullable=False),
    ],
    table_constraints=[
        'first_approved_by IS NULL OR first_approved_by <> requested_by',
        '(second_approved_by IS NULL OR second_approved_by <> requested_by) AND (second_approved_by IS NULL OR first_approved_by IS NULL OR second_approved_by <> first_approved_by)',
    ],
    actions=[
        ActionDef(
            name="create_approval_record_pending",
            function_type="insert",
            transition=StateTransition(from_state="init", to_state="pending"),
        ),
        ActionDef(
            name="create_approval_record_pending_bulk",
            function_type="bulk_insert",
            transition=StateTransition(from_state="init", to_state="pending"),
        ),
        ActionDef(
            name="set_approval_record_cancelled_from_pending",
            function_type="update",
            transition=StateTransition(from_state="pending", to_state="cancelled"),
        ),
        ActionDef(
            name="set_approval_record_cancelled_from_pending_bulk",
            function_type="bulk_update",
            transition=StateTransition(from_state="pending", to_state="cancelled"),
        ),
        ActionDef(
            name="set_approval_record_approved_from_pending",
            function_type="update",
            transition=StateTransition(from_state="pending", to_state="approved"),
        ),
        ActionDef(
            name="set_approval_record_approved_from_pending_bulk",
            function_type="bulk_update",
            transition=StateTransition(from_state="pending", to_state="approved"),
        ),
        ActionDef(
            name="set_approval_record_verifying_from_pending",
            function_type="update",
            transition=StateTransition(from_state="pending", to_state="verifying"),
        ),
        ActionDef(
            name="set_approval_record_verifying_from_pending_bulk",
            function_type="bulk_update",
            transition=StateTransition(from_state="pending", to_state="verifying"),
        ),
        ActionDef(
            name="set_approval_record_rework_from_pending",
            function_type="update",
            transition=StateTransition(from_state="pending", to_state="rework"),
        ),
        ActionDef(
            name="set_approval_record_rework_from_pending_bulk",
            function_type="bulk_update",
            transition=StateTransition(from_state="pending", to_state="rework"),
        ),
        ActionDef(
            name="set_approval_record_approved_from_verifying",
            function_type="update",
            transition=StateTransition(from_state="verifying", to_state="approved"),
        ),
        ActionDef(
            name="set_approval_record_approved_from_verifying_bulk",
            function_type="bulk_update",
            transition=StateTransition(from_state="verifying", to_state="approved"),
        ),
        ActionDef(
            name="set_approval_record_rework_from_verifying",
            function_type="update",
            transition=StateTransition(from_state="verifying", to_state="rework"),
        ),
        ActionDef(
            name="set_approval_record_rework_from_verifying_bulk",
            function_type="bulk_update",
            transition=StateTransition(from_state="verifying", to_state="rework"),
        ),
        ActionDef(
            name="set_approval_record_cancelled_from_rework",
            function_type="update",
            transition=StateTransition(from_state="rework", to_state="cancelled"),
        ),
        ActionDef(
            name="set_approval_record_cancelled_from_rework_bulk",
            function_type="bulk_update",
            transition=StateTransition(from_state="rework", to_state="cancelled"),
        ),
        ActionDef(
            name="set_approval_record_pending_from_rework",
            function_type="update",
            transition=StateTransition(from_state="rework", to_state="pending"),
        ),
        ActionDef(
            name="set_approval_record_pending_from_rework_bulk",
            function_type="bulk_update",
            transition=StateTransition(from_state="rework", to_state="pending"),
        ),
        ActionDef(
            name="set_approval_record_applied_from_approved",
            function_type="update",
            transition=StateTransition(from_state="approved", to_state="applied"),
        ),
        ActionDef(
            name="set_approval_record_applied_from_approved_bulk",
            function_type="bulk_update",
            transition=StateTransition(from_state="approved", to_state="applied"),
        ),
    ],
)
