from lib import (
    ActionDef,
    ColumnDef,
    FKDefinition,
    PKConfig,
    StateTransition,
    TableConfig,
)

config = TableConfig(
    table_name="debts",
    pk_field="product_id",
    pk_config=PKConfig(strategy="custom", generator=lambda data: data["product_id"]),
    states=['active', 'disabled'],
    transitions=[
        StateTransition(from_state="init", to_state="active"),
        StateTransition(from_state="active", to_state="active"),
        StateTransition(from_state="active", to_state="disabled"),
    ],
    columns=[
        ColumnDef(name="product_id", pg_type="varchar(50)", nullable=False),
        ColumnDef(name="name", pg_type="text", nullable=True),
        ColumnDef(name="currency", pg_type="char(3)", nullable=True),
        ColumnDef(name="issuance_date", pg_type="date", nullable=True),
        ColumnDef(name="maturity_date", pg_type="date", nullable=True),
        ColumnDef(name="seniority", pg_type="varchar(50)", nullable=True),
        ColumnDef(name="coupon_rate", pg_type="numeric(10,6)", nullable=True),
        ColumnDef(name="coupon_type", pg_type="varchar(50)", nullable=True),
        ColumnDef(name="day_count_fraction", pg_type="varchar(50)", nullable=True),
        ColumnDef(name="issuer_party_id", pg_type="varchar(50)", nullable=True),
        ColumnDef(name="issuer_party_name", pg_type="text", nullable=True),
        ColumnDef(name="payment_frequency", pg_type="varchar(50)", nullable=True),
        ColumnDef(name="face_amount", pg_type="numeric(20,2)", nullable=True),
        ColumnDef(name="par_value", pg_type="numeric(20,2)", nullable=True),
        ColumnDef(name="pool", pg_type="boolean", nullable=True),
        ColumnDef(name="insurer_party_id", pg_type="varchar(50)", nullable=True),
        ColumnDef(name="insurer_party_name", pg_type="text", nullable=True),
        ColumnDef(name="sector", pg_type="varchar(50)", nullable=True),
        ColumnDef(name="tranche", pg_type="varchar(50)", nullable=True),
        ColumnDef(name="exercise_style", pg_type="varchar(50)", nullable=True),
        ColumnDef(name="exercise_date", pg_type="date", nullable=True),
        ColumnDef(name="option_type", pg_type="varchar(50)", nullable=True),
        ColumnDef(name="strike", pg_type="numeric(20,2)", nullable=True),
        ColumnDef(name="strike_currency", pg_type="char(3)", nullable=True),
        ColumnDef(name="strike_units", pg_type="varchar(50)", nullable=True),
        ColumnDef(name="issue_size", pg_type="bigint", nullable=True),
        ColumnDef(name="circulation_size", pg_type="bigint", nullable=True),
        ColumnDef(name="source", pg_type="varchar(50)", nullable=True),
        ColumnDef(name="state", pg_type="text", nullable=False),
    ],
    table_constraints=[
        'maturity_date IS NULL OR issuance_date IS NULL OR issuance_date <= maturity_date',
    ],
    fk_definitions=[
        FKDefinition(field="product_id", referenced_table="products", referenced_field="product_id"),
        FKDefinition(field="currency", referenced_table="currency_code", referenced_field="code"),
        FKDefinition(field="day_count_fraction", referenced_table="day_count_basis", referenced_field="dcb"),
        FKDefinition(field="payment_frequency", referenced_table="frequency", referenced_field="frequency"),
        FKDefinition(field="sector", referenced_table="industry_type_list", referenced_field="type"),
        FKDefinition(field="strike_currency", referenced_table="currency_code", referenced_field="code"),
        FKDefinition(field="strike_units", referenced_table="uom_type", referenced_field="type"),
        FKDefinition(field="source", referenced_table="source", referenced_field="source_code"),
    ],
    actions=[
        ActionDef(
            name="create_debts_active",
            function_type="insert",
            transition=StateTransition(from_state="init", to_state="active"),
        ),
        ActionDef(
            name="create_debts_active_bulk",
            function_type="bulk_insert",
            transition=StateTransition(from_state="init", to_state="active"),
        ),
        ActionDef(
            name="update_debts_active",
            function_type="update",
            transition=StateTransition(from_state="active", to_state="active"),
        ),
        ActionDef(
            name="update_debts_active_bulk",
            function_type="bulk_update",
            transition=StateTransition(from_state="active", to_state="active"),
        ),
        ActionDef(
            name="set_debts_disabled_from_active",
            function_type="update",
            transition=StateTransition(from_state="active", to_state="disabled"),
        ),
        ActionDef(
            name="set_debts_disabled_from_active_bulk",
            function_type="bulk_update",
            transition=StateTransition(from_state="active", to_state="disabled"),
        ),
    ],
)
