from lib import (
    ActionDef,
    ColumnDef,
    FKDefinition,
    PKConfig,
    StateTransition,
    TableConfig,
)

config = TableConfig(
    table_name="party_person",
    pk_field="party_id",
    pk_config=PKConfig(strategy="custom", generator=lambda data: data["party_id"]),
    states=["draft", "active", "disabled"],
    transitions=[
        StateTransition(from_state="init", to_state="draft"),
        StateTransition(from_state="init", to_state="active"),
        StateTransition(from_state="draft", to_state="draft"),
        StateTransition(from_state="draft", to_state="active"),
        StateTransition(from_state="active", to_state="active"),
        StateTransition(from_state="active", to_state="disabled"),
        StateTransition(from_state="disabled", to_state="deleted"),
    ],
    columns=[
        ColumnDef(name="party_id",             pg_type="text", nullable=False),
        ColumnDef(name="title",                pg_type="text", nullable=True),
        ColumnDef(name="first_name",           pg_type="text", nullable=False),
        ColumnDef(name="last_name",            pg_type="text", nullable=False),
        ColumnDef(name="mid_name",             pg_type="text", nullable=True),
        ColumnDef(name="preferred_name",       pg_type="text", nullable=True),
        ColumnDef(name="first_name_local",     pg_type="text", nullable=True),
        ColumnDef(name="last_name_local",      pg_type="text", nullable=True),
        ColumnDef(name="mid_name_local",       pg_type="text", nullable=True),
        ColumnDef(name="preferred_name_local", pg_type="text", nullable=True),
        ColumnDef(name="local_lang",           pg_type="text", nullable=True),
        ColumnDef(name="gender",               pg_type="text", nullable=True),
        ColumnDef(name="date_of_birth",        pg_type="date", nullable=True),
        ColumnDef(name="nationality",          pg_type="text", nullable=True),
        ColumnDef(name="country_of_residence", pg_type="text", nullable=True),
        ColumnDef(name="country_of_birth",     pg_type="text", nullable=True),
        ColumnDef(name="education_level",      pg_type="text", nullable=True),
        ColumnDef(name="marital_status",       pg_type="text", nullable=True),
        ColumnDef(name="state",                pg_type="text", nullable=False),
    ],
    fk_definitions=[
        FKDefinition(
            field="party_id",
            referenced_table="party",
            referenced_field="party_id",
            on_update="CASCADE",
            on_delete="CASCADE",
        ),
        FKDefinition(
            field="local_lang",
            referenced_table="language",
            referenced_field="language_code",
            on_update="CASCADE",
            on_delete="RESTRICT",
        ),
        FKDefinition(
            field="nationality",
            referenced_table="country",
            referenced_field="country_code",
            on_update="CASCADE",
            on_delete="RESTRICT",
        ),
        FKDefinition(
            field="country_of_residence",
            referenced_table="country",
            referenced_field="country_code",
            on_update="CASCADE",
            on_delete="RESTRICT",
        ),
        FKDefinition(
            field="country_of_birth",
            referenced_table="country",
            referenced_field="country_code",
            on_update="CASCADE",
            on_delete="RESTRICT",
        ),
        FKDefinition(
            field="education_level",
            referenced_table="education_level_list",
            referenced_field="code",
            on_update="CASCADE",
            on_delete="RESTRICT",
        ),
        FKDefinition(
            field="marital_status",
            referenced_table="marital_status_list",
            referenced_field="code",
            on_update="CASCADE",
            on_delete="RESTRICT",
        ),
    ],
    actions=[
        ActionDef(
            name="create_party_person_draft",
            function_type="insert",
            transition=StateTransition(from_state="init", to_state="draft"),
        ),
        ActionDef(
            name="create_party_person_active",
            function_type="insert",
            transition=StateTransition(from_state="init", to_state="active"),
        ),
        ActionDef(
            name="create_party_person_bulk",
            function_type="bulk_insert",
            transition=StateTransition(from_state="init", to_state="active"),
        ),
        ActionDef(
            name="update_party_person_draft",
            function_type="update",
            transition=StateTransition(from_state="draft", to_state="draft"),
        ),
        ActionDef(
            name="activate_party_person",
            function_type="update",
            transition=StateTransition(from_state="draft", to_state="active"),
        ),
        ActionDef(
            name="party_person_update",
            function_type="update",
            transition=StateTransition(from_state="active", to_state="active"),
        ),
        ActionDef(
            name="disable_party_person",
            function_type="update",
            transition=StateTransition(from_state="active", to_state="disabled"),
        ),
        ActionDef(
            name="disable_party_person_bulk",
            function_type="bulk_update",
            transition=StateTransition(from_state="active", to_state="disabled"),
        ),
        ActionDef(
            name="delete_party_person",
            function_type="delete",
            transition=StateTransition(from_state="disabled", to_state="deleted"),
        ),
        ActionDef(
            name="delete_party_person_bulk",
            function_type="bulk_delete",
            transition=StateTransition(from_state="disabled", to_state="deleted"),
        ),
    ],
)
